baseURL = 'https://malleo.dev/'
languageCode = 'en-us'
title = 'Hardening Your AI by breaking it first'
theme = 'hello-friend-ng'

[params]
  homeSubtitle = "Your Agents will break. We make sure it happens on your own terms through adversarial testing and cognitive red teaming."
  enableThemeToggle = true

  [params.logo]
    logoMark     = ">"
    logoText     = "malleo"
    logoHomeLink = "/"

  [[params.social]]
    name = "email"
    url  = "mailto:malleo@jellyfish.mozmail.com"
